apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: jobboard-kafka
  namespace: kafka
  annotations:
    strimzi.io/node-pools: "enabled"
    strimzi.io/kraft: "enabled"
spec:
  kafka:
    version: 4.1.1

    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false

    config:
      process.roles: "broker,controller"
      controller.listener.names: "CONTROLLER"
      listeners: "PLAINTEXT://:9092,CONTROLLER://:9093"
      listener.security.protocol.map: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT"
      inter.broker.listener.name: "PLAINTEXT"

      offsets.topic.replication.factor: 2
      transaction.state.log.replication.factor: 2
      transaction.state.log.min.isr: 1
      default.replication.factor: 2
      min.insync.replicas: 1

      auto.create.topics.enable: "false"

  entityOperator:
    topicOperator: {}
    userOperator: {}
