apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: jobboard-kafka
  namespace: kafka
  annotations:
    strimzi.io/node-pools: "enabled"
    strimzi.io/kraft: "enabled"
spec:
  kafka:
    version: 4.1.1
    replicas: 3

    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false

    config:
      # KRaft mode (no ZooKeeper)
      process.roles: "broker,controller"
      controller.listener.names: "CONTROLLER"
      listeners: "PLAINTEXT://:9092,CONTROLLER://:9093"
      listener.security.protocol.map: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT"
      inter.broker.listener.name: "PLAINTEXT"

      # Replication sane defaults (works with 3 brokers, topics RF=2)
      offsets.topic.replication.factor: 2
      transaction.state.log.replication.factor: 2
      transaction.state.log.min.isr: 1
      default.replication.factor: 2
      min.insync.replicas: 1

      # Optional (safe defaults)
      auto.create.topics.enable: "false"

    storage:
      type: jbod
      volumes:
        - id: 0
          type: persistent-claim
          size: 20Gi
          class: longhorn
          deleteClaim: false

    resources:
      requests:
        cpu: 500m
        memory: 1Gi
      limits:
        cpu: "2"
        memory: 4Gi

    template:
      pod:
        terminationGracePeriodSeconds: 60

  entityOperator:
    topicOperator: {}
    userOperator: {}
