apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: jobboard-kafka
  namespace: kafka
  labels:
    app: kafka
    cluster: jobboard
spec:
  kafka:
    version: 3.9.0
    replicas: 3
    
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
    
    config:
      offsets.topic.replication.factor: 2
      transaction.state.log.replication.factor: 2
      transaction.state.log.min.isr: 2
      default.replication.factor: 2
      min.insync.replicas: 2
      num.network.threads: 3
      num.io.threads: 8
      log.retention.hours: 168
      log.retention.bytes: 10737418240
      auto.create.topics.enable: true
      delete.topic.enable: true
    
    storage:
      type: persistent-claim
      size: 20Gi
      class: longhorn
      deleteClaim: false
    
    resources:
      requests:
        memory: 1Gi
        cpu: 500m
      limits:
        memory: 2Gi
        cpu: 2000m
    
    jvmOptions:
      -Xms: 512m
      -Xmx: 1536m
    
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          name: kafka-metrics
          key: kafka-metrics-config.yml
  
  zookeeper:
    replicas: 3
    
    storage:
      type: persistent-claim
      size: 10Gi
      class: longhorn
      deleteClaim: false
    
    resources:
      requests:
        memory: 512Mi
        cpu: 250m
      limits:
        memory: 1Gi
        cpu: 1000m
    
    jvmOptions:
      -Xms: 256m
      -Xmx: 512m
    
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          name: kafka-metrics
          key: zookeeper-metrics-config.yml
  
  entityOperator:
    topicOperator:
      resources:
        requests:
          memory: 256Mi
          cpu: 100m
        limits:
          memory: 512Mi
          cpu: 500m
    
    userOperator:
      resources:
        requests:
          memory: 256Mi
          cpu: 100m
        limits:
          memory: 512Mi
          cpu: 500m
  
  kafkaExporter:
    topicRegex: ".*"
    groupRegex: ".*"
    resources:
      requests:
        memory: 128Mi
        cpu: 100m
      limits:
        memory: 256Mi
        cpu: 500m
