apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: pool-a
  namespace: kafka
  labels:
    strimzi.io/cluster: jobboard-kafka
spec:
  replicas: 3
  roles:
    - controller
    - broker

  storage:
    type: persistent-claim
    size: 20Gi
    class: longhorn
    deleteClaim: false

  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: "2"
      memory: 4Gi
