apiVersion: v1
kind: Secret
metadata:
  name: operator-oauth
  namespace: tailscale-system
stringData:
  client_id: kSBztUWaZs11CNTRL
  client_secret: tskey-client-kSBztUWaZs11CNTRL-BiP7NvsVqx9pW5noPWzAx94yh6dvE7FE
