apiVersion: v1
kind: Secret
metadata:
  name: operator-oauth
  namespace: tailscale-system
stringData:
  client_id: k38Z7mdb8521CNTRL
  client_secret: tskey-client-k38Z7mdb8521CNTRL-K6CaHTL6znbUCr5KCm8aobG1AZDxsJeD
