apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-serve-config
  namespace: argocd
data:
  serve.json: |
    {
      "TCP": {
        "443": {
          "HTTPS": true
        }
      },
      "Web": {
        "argocd-au.tail-scale.ts.net:443": {
          "Handlers": {
            "/": {
              "Proxy": "http://argocd-server.argocd.svc.cluster.local:80"
            }
          }
        }
      }
    }
---
apiVersion: v1
kind: Pod
metadata:
  name: tailscale-argocd
  namespace: argocd
  labels:
    app: tailscale-serve
spec:
  serviceAccountName: tailscale
  containers:
  - name: tailscale
    image: tailscale/tailscale:latest
    env:
    - name: TS_AUTHKEY
      valueFrom:
        secretKeyRef:
          name: tailscale-auth
          key: TS_AUTHKEY
    - name: TS_HOSTNAME
      value: "argocd-au"
    - name: TS_STATE_DIR
      value: "/var/lib/tailscale"
    - name: TS_SERVE_CONFIG
      value: "/config/serve.json"
    volumeMounts:
    - name: tailscale-state
      mountPath: /var/lib/tailscale
    - name: serve-config
      mountPath: /config
  volumes:
  - name: tailscale-state
    emptyDir: {}
  - name: serve-config
    configMap:
      name: argocd-serve-config
