apiVersion: v1
kind: Pod
metadata:
  name: tailscale-argocd
  namespace: argocd
spec:
  serviceAccountName: tailscale
  containers:
  - name: tailscale
    image: tailscale/tailscale:latest
    env:
    - name: TS_AUTHKEY
      valueFrom:
        secretKeyRef:
          name: tailscale-auth
          key: TS_AUTHKEY
    - name: TS_HOSTNAME
      value: "argocd-au"
    - name: TS_STATE_DIR
      value: "/var/lib/tailscale"
    - name: TS_USERSPACE
      value: "true"
    command:
    - sh
    - -c
    - |
      /usr/local/bin/containerboot &
      sleep 10
      tailscale serve --bg --https 443 http://argocd-server.argocd.svc.cluster.local:80
      wait
    volumeMounts:
    - name: tailscale-state
      mountPath: /var/lib/tailscale
  volumes:
  - name: tailscale-state
    emptyDir: {}
