apiVersion: v1
kind: Secret
metadata:
  name: tailscale-auth
  namespace: argocd
type: Opaque
stringData:
  TS_AUTHKEY: tskey-auth-kaiHjSExSS11CNTRL-GTkCqs3hwAjofTHS7UCcBjtQNkGqYAsPE
  TS_CLIENT_ID: kSBztUWaZs11CNTRL
  TS_CLIENT_SECRET: tskey-client-kSBztUWaZs11CNTRL-BiP7NvsVqx9pW5noPWzAx94yh6dvE7FE
