apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-to-victorialogs-script
  namespace: logs-backup
data:
  shipper.sh: |
    #!/usr/bin/env sh
    set -eu

    LOKI_URL="${LOKI_URL:-http://observability-loki.loki.svc.cluster.local:3100}"
    VLOGS_PUSH_URL="${VLOGS_PUSH_URL:-http://victorialogs.logs-backup.svc.cluster.local:9428/insert/loki/api/v1/push}"
    WINDOW_SECONDS="${WINDOW_SECONDS:-300}"   # last 5 minutes
    SLEEP_SECONDS="${SLEEP_SECONDS:-60}"      # every 60 seconds

    while true; do
      END_NS=$(date +%s)000000000
      START_NS=$(( ( $(date +%s) - WINDOW_SECONDS ) * 1000000000 ))

      # Query Loki for raw log entries in the time window.
      # We fetch as streams and re-push the same Loki JSON payload format to VictoriaLogs.
      # Loki query_range returns streams in JSON; VictoriaLogs accepts Loki push JSON at /insert/loki/api/v1/push.
      echo "[shipper] pulling Loki logs last ${WINDOW_SECONDS}s..."
      RESP="$(curl -sS --fail "${LOKI_URL}/loki/api/v1/query_range?query=%7B%7D&start=${START_NS}&end=${END_NS}&limit=5000")"

      # Convert Loki query_range response into Loki push payload.
      # Loki query_range: { data: { result: [ { stream: {...}, values: [[ts, line], ...] } ] } }
      # Loki push:       { streams: [ { stream: {...}, values: [[ts, line], ...] } ] }
      PAYLOAD="$(echo "$RESP" | jq -c '{streams: .data.result}')" || true

      if [ -n "${PAYLOAD:-}" ] && [ "$(echo "$PAYLOAD" | jq '.streams | length')" -gt 0 ]; then
        echo "[shipper] pushing to VictoriaLogs..."
        curl -sS --fail -X POST \
          -H "Content-Type: application/json" \
          --data-binary "$PAYLOAD" \
          "$VLOGS_PUSH_URL" >/dev/null
        echo "[shipper] pushed."
      else
        echo "[shipper] nothing to push."
      fi

      sleep "$SLEEP_SECONDS"
    done
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki-to-victorialogs
  namespace: logs-backup
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loki-to-victorialogs
  template:
    metadata:
      labels:
        app: loki-to-victorialogs
    spec:
      containers:
        - name: shipper
          image: alpine:3.20
          command: ["/bin/sh", "-lc"]
          args:
            - apk add --no-cache curl jq && chmod +x /scripts/shipper.sh && /scripts/shipper.sh
          env:
            - name: LOKI_URL
              value: http://observability-loki.loki.svc.cluster.local:3100
            - name: VLOGS_PUSH_URL
              value: http://victorialogs.logs-backup.svc.cluster.local:9428/insert/loki/api/v1/push
            - name: WINDOW_SECONDS
              value: "300"
            - name: SLEEP_SECONDS
              value: "60"
          volumeMounts:
            - name: scripts
              mountPath: /scripts
      volumes:
        - name: scripts
          configMap:
            name: loki-to-victorialogs-script
            defaultMode: 0755
