apiVersion: v1
kind: ServiceAccount
metadata:
  name: vector
  namespace: logs-backup
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vector-kubernetes
rules:
  - apiGroups: [""]
    resources: ["pods", "namespaces", "nodes"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vector-kubernetes
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: vector-kubernetes
subjects:
  - kind: ServiceAccount
    name: vector
    namespace: logs-backup
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vector-config
  namespace: logs-backup
data:
  vector.yaml: |
    data_dir: /vector-data-dir

    sources:
      kubernetes_logs:
        type: kubernetes_logs

    transforms:
      add_k8s_labels:
        type: remap
        inputs: [kubernetes_logs]
        source: |
          .labels = {}
          if exists(.kubernetes.namespace) { .labels.namespace = .kubernetes.namespace }
          if exists(.kubernetes.pod_name) { .labels.pod = .kubernetes.pod_name }
          if exists(.kubernetes.container_name) { .labels.container = .kubernetes.container_name }
          if exists(.kubernetes.node_name) { .labels.node = .kubernetes.node_name }

    sinks:
      # PRIMARY: Loki
      loki:
        type: loki
        inputs: [add_k8s_labels]
        endpoint: http://observability-loki.loki.svc.cluster.local:3100
        encoding:
          codec: json
        labels:
          namespace: "{{ labels.namespace }}"
          pod: "{{ labels.pod }}"
          container: "{{ labels.container }}"
          node: "{{ labels.node }}"

      # BACKUP: VictoriaLogs (Loki JSON ingest endpoint)
      victorialogs:
        type: loki
        inputs: [add_k8s_labels]
        endpoint: http://victorialogs.logs-backup.svc.cluster.local:9428
        path: /insert/loki/api/v1/push
        encoding:
          codec: json
        labels:
          namespace: "{{ labels.namespace }}"
          pod: "{{ labels.pod }}"
          container: "{{ labels.container }}"
          node: "{{ labels.node }}"
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: vector
  namespace: logs-backup
spec:
  selector:
    matchLabels:
      app: vector
  template:
    metadata:
      labels:
        app: vector
    spec:
      serviceAccountName: vector
      containers:
        - name: vector
          image: timberio/vector:0.42.0-alpine
          args: ["-c", "/etc/vector/vector.yaml"]
          volumeMounts:
            - name: varlog
              mountPath: /var/log
              readOnly: true
            - name: config
              mountPath: /etc/vector
      volumes:
        - name: varlog
          hostPath:
            path: /var/log
        - name: config
          configMap:
            name: vector-config
