apiVersion: v1
kind: ServiceAccount
metadata:
  name: vector
  namespace: logs-backup
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vector-kubernetes
rules:
  - apiGroups: [""]
    resources: ["pods", "namespaces", "nodes"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vector-kubernetes
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: vector-kubernetes
subjects:
  - kind: ServiceAccount
    name: vector
    namespace: logs-backup
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vector-config
  namespace: logs-backup
data:
  vector.yaml: |
    data_dir: /vector-data-dir

    sources:
      kubernetes_logs:
        type: kubernetes_logs

    transforms:
      add_k8s_labels:
        type: remap
        inputs: [kubernetes_logs]
        source: |
          # normalize common fields for both backends
          .labels = {}
          if exists(.kubernetes.namespace) { .labels.namespace = .kubernetes.namespace }
          if exists(.kubernetes.pod_name) { .labels.pod = .kubernetes.pod_name }
          if exists(.kubernetes.container_name) { .labels.container = .kubernetes.container_name }
          if exists(.kubernetes.node_name) { .labels.node = .kubernetes.node_name }

    sinks:
      # PRIMARY: Loki
      loki:
        type: loki
        inputs: [add_k8s_labels]
        endpoint: http://observability-loki.loki.svc.cluster.local:3100
        encoding:
          codec: json
        labels:
          namespace: "{{ labels.namespace }}"
          pod: "{{ labels.pod }}"
          container: "{{ labels.container }}"
          node: "{{ labels.node }}"

      # BACKUP: VictoriaLogs using Loki JSON push-compatible ingest
      victorialogs:
        type: http
        inputs: [add_k8s_labels]
        uri: http://victorialogs.logs-backup.svc.cluster.local:9428/insert/loki/api/v1/push
        method: post
        encoding:
          codec: json
        request:
          headers:
            Content-Type: application/json
        # Vector's loki sink builds Loki push format; for HTTP sink we need it too.
        # We'll send Loki-compatible payload using the same record structure.
        # (This works because VictoriaLogs accepts Loki JSON API format). 
        # If you want maximum safety, we can switch this sink to Vector's native 'loki' sink
        # once your Vector version supports custom path.
        batch:
          max_bytes: 1048576
          timeout_secs: 2
