apiVersion: v1
kind: Namespace
metadata:
  name: logs-backup
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: victorialogs-data
  namespace: logs-backup
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: victorialogs
  namespace: logs-backup
spec:
  replicas: 1
  selector:
    matchLabels:
      app: victorialogs
  template:
    metadata:
      labels:
        app: victorialogs
    spec:
      containers:
        - name: victorialogs
          image: victoriametrics/victoria-logs:latest
          args:
            - -storageDataPath=/victoria-logs-data
          ports:
            - name: http
              containerPort: 9428
          volumeMounts:
            - name: data
              mountPath: /victoria-logs-data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: victorialogs-data
---
apiVersion: v1
kind: Service
metadata:
  name: victorialogs
  namespace: logs-backup
spec:
  selector:
    app: victorialogs
  ports:
    - name: http
      port: 9428
      targetPort: 9428
