apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka-consumers
  namespace: argocd
  labels:
    argocd.argoproj.io/instance: root
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: default
  source:
    repoURL: https://github.com/smjobboardapp/jobboard-gitops.git
    targetRevision: main
    path: apps/consumers
  destination:
    server: https://kubernetes.default.svc
    namespace: kafka
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 5m
