apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: logs-promtail
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://grafana.github.io/helm-charts
      chart: promtail
      targetRevision: 6.16.6
      helm:
        valueFiles:
          - $values/infra/logs/promtail-values.yaml
    - repoURL: https://github.com/smjobboardapp/jobboard-gitops.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: logs
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
