apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: logs-backup
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/smjobboardapp/jobboard-gitops.git
    targetRevision: HEAD
    path: apps/logs-backup
  destination:
    server: https://kubernetes.default.svc
    namespace: logs-backup
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
