apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: observability-metrics
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: kube-prometheus-stack
      targetRevision: "80.4.1"
      helm:
        valueFiles:
          - $values/infra/observability/kps/values.yaml
    - repoURL: https://github.com/smjobboardapp/jobboard-gitops.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
