apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: observability-loki
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/grafana/helm-charts.git
      targetRevision: main
      path: charts/loki-stack
      helm:
        valueFiles:
          - $values/infra/observability/loki/values.yaml
    - repoURL: https://github.com/smjobboardapp/jobboard-gitops.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: loki
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
