apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tailscale-serve
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/smjobboardapp/jobboard-gitops.git
    targetRevision: HEAD
    path: infra/tailscale-serve
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
